### PR TITLE
NappDrawer 1.1.5.RC

### PR DESCRIPTION
**Pull request by mano-mykingdom**
made compatible with 1.1.5.RC

### CODE REVIEW

**Comment by FokkeZB** [comment]
Did you test this using the [test](https://github.com/FokkeZB/nl.fokkezb.drawer/tree/test) branch on each of the platforms and with both the current and 1.1.5.RC version of NappDrawer and the current drawerLayout module?

**Comment by mano-mykingdom** [comment]
@FokkeZB I have tested using test branch, with both current and 1.1.5.RC version of NappDrawer as well as both Ti SDK 3.5.1.GA and 4.0.0.RC. Everything is working fine.

**Comment by FokkeZB** [comment]
I believe you for it since I don't have time right now to test ;)

**Comment by mano-mykingdom** [comment]
There is a open issue with NappDrawer [#159](https://github.com/viezel/NappDrawer/issues/159). Setting `useArrowAnimation` to `true` wont work until `didChangeOffset` listener is added.

**Pull request merged**
